{
 "title": "OCNRF Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(container_memory_usage_bytes{namespace=~\".+\",container_name!=\"POD\"},namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "OCNRF API-Gateway Request Latency (Heatmap)",
   "type": "heatmap",
   "description": "Latency time displayed as a histogram over time",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "  rate(apigateway_request_latency_seconds_bucket[10m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "OCNRF API-Gateway Request Latency (Histogram)",
   "type": "graph",
   "description": "Histogram",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(apigateway_request_latency_seconds_sum[5m])/rate(apigateway_request_latency_seconds_count[5m])",
     "legendFormat": "Avg NRF Latency"
    }
   ]
  },
  {
   "title": "OCNRF API-Gateway Egress Response Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  sum(irate(apigateway_http_responses_total[2m])) by (kubernetes_namespace,app)",
     "legendFormat": "Egress Response Rate"
    }
   ]
  },
  { "title": "Overall Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  { "title": "Service Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Registration Service Success (2xx) %",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(apigateway_http_responses_total{Status=~\"2.*\",Uri=~\".*nnrf-nfm/v1/nf-instances.*\"})/sum(apigateway_http_responses_total{Uri=~\".*nnrf-nfm/v1/nf-instances.*\"})*100"
    }
   ]
  },
  {
   "title": "Subscription Service Success (2xx) %",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(apigateway_http_responses_total{Status=~\"2.*\",Uri=~\".*nnrf-nfm/v1/subscriptions.*\"})/sum(apigateway_http_responses_total{Uri=~\".*nnrf-nfm/v1/subscriptions.*\"})*100"
    }
   ]
  },
  {
   "title": "Discover Service Success (2xx) %",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(apigateway_http_responses_total{Status=~\"2.*\",Uri=~\".*nnrf-disc/v1/nf-instances.*\"})/sum(apigateway_http_responses_total{Uri=~\".*nnrf-disc/v1/nf-instances.*\"})*100"
    }
   ]
  },
  {
   "title": "Registrations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(apigateway_http_responses_total{Status = \"200 OK\"}[5m]))/20",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum(increase(apigateway_http_responses_total{Status=\"201 CREATED\"}[5m]))/20",
     "legendFormat": "Creates"
    },
    {
     "expr": "sum(increase(apigateway_http_responses_total{Status=\"204 NO_CONTENT\"}[5m]))/20",
     "legendFormat": "Deletes"
    },
    {
     "expr": "sum(increase(apigateway_http_responses_total{Status=~\"4.*\"}[5m]))/20",
     "legendFormat": "(4xx)"
    },
    {
     "expr": "ocnrf_nfRegister_rx_requests_total{kubernetes_namespace=\"$namespace\"}                                                                                                                      ",
     "legendFormat": "NfRegister Req {{ OriginatorNfType }} {{NrfLevel }} {{NfInstanceId }}"
    },
    {
     "expr": "ocnrf_nfRegister_tx_responses_total{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "NfRegister Resp {{ OriginatorNfType }} {{ HttpStatusCode }}"
    },
    {
     "expr": "sum(ocnrf_nfRegister_rx_requests_total{kubernetes_namespace=\"$namespace\"})",
     "legendFormat": "NfRegistrations Total"
    },
    {
     "expr": "ocnrf_nfRegister_rx_requests_success_perService_total{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "NfRegistrations Per Service {{ serviceName }}"
    },
    {
     "expr": "ocnrf_active_registrations_count{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "Active Registrations {{ NfType }} {{ NrfLevel }}"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(apigateway_http_responses_total{Status=\"201 CREATED\"}[5m]))",
     "legendFormat": "Creates"
    },
    {
     "expr": "sum(increase(apigateway_http_responses_total{Status=\"204 NO_CONTENT\"}[5m]))",
     "legendFormat": "Deletes"
    },
    {
     "expr": "sum(increase(apigateway_http_responses_total{Status=~\"4.*\"}[5m]))",
     "legendFormat": "(4xx)"
    },
    {
     "expr": "sum(increase(apigateway_http_responses_total{Status=~\"5.*\"}[5m]))",
     "legendFormat": "(5xx)"
    },
    {
     "expr": "ocnrf_nfStatusSubscribe_rx_requests_total{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "{{ OperationType }} Subscriptions - {{ OriginatorNfType }}"
    }
   ]
  },
  {
   "title": "Discovery",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(apigateway_http_responses_total{Status=\"200 OK\"}[5m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(apigateway_http_responses_total{Status=~\"4.*\"}[5m]))",
     "legendFormat": "(4xx)"
    },
    {
     "expr": "sum(increase(apigateway_http_responses_total{Status=~\"5.*\"}[5m]))",
     "legendFormat": "(5xx)"
    },
    {
     "expr": "ocnrf_nfDiscover_rx_requests_total{kubernetes_namespace=\"$namespace\",NrfLevel=\"default-ocnrf\"}",
     "legendFormat": "NfDiscover Req - TargetNf: {{ TargetNfType }}"
    },
    {
     "expr": "ocnrf_nfDiscover_profiles_discovered_total{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "Discovered profiles {{ Bucket }}"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Cpu usage (per service)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=\"nfregistration\", kubernetes_namespace=\"$namespace\"}[2m])) ",
     "legendFormat": "nfregistration"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=\"nfsubscription\", kubernetes_namespace=\"$namespace\"}[2m]))",
     "legendFormat": "nfsubscription"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=\"nfdiscovery\", kubernetes_namespace=\"$namespace\"}[2m]))",
     "legendFormat": "nfdiscovery"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=\"nrfauditor\", kubernetes_namespace=\"$namespace\"}[2m]))",
     "legendFormat": "nrfauditor"
    }
   ]
  },
  {
   "title": "Total Replicas",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_hpa_status_current_replicas{hpa=\"hp-autoscaler-nfregistration\", kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "nfregistration"
    },
    {
     "expr": "kube_hpa_status_current_replicas{hpa=\"hp-autoscaler-nfsubscription\", kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "nfsubscription"
    },
    {
     "expr": "kube_hpa_status_current_replicas{hpa=\"hp-autoscaler-nfdiscovery\", kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "nfdiscovery"
    }
   ]
  },
  {
   "title": "Memory usage (per service)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{container_name=\"nfregistration\", kubernetes_namespace=\"$namespace\"})",
     "legendFormat": "nfregistration"
    },
    {
     "expr": "sum (container_memory_usage_bytes{container_name=\"nfsubscription\", kubernetes_namespace=\"$namespace\"})",
     "legendFormat": "nfsubscription"
    },
    {
     "expr": "sum (container_memory_usage_bytes{container_name=\"nfdiscovery\", kubernetes_namespace=\"$namespace\"})",
     "legendFormat": "nfdiscovery"
    },
    {
     "expr": "sum (container_memory_usage_bytes{container_name=\"nrfauditor\", kubernetes_namespace=\"$namespace\"})",
     "legendFormat": "nrfauditor"
    }
   ]
  }
 ]
}