{
 "title": "OCSCP Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "2s",
 "panels": [
  {
   "title": "Ingress Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ocscp_metric_total_http_rx_req[2m])) ",
     "legendFormat": "Ingress Request Rate"
    },
    {
     "expr": "sum(irate(ocscp_metric_total_http_rx_req[2m])) by (ocscp_nf_type)",
     "legendFormat": "{{ocscp_nf_type}}"
    }
   ]
  },
  {
   "title": "Transaction Success Rate (nfType)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(irate(ocscp_metric_total_http_tx_res_xx{ocscp_response_code_class=\"2\", ocscp_nf_type=~\"NRF|UDM|PCF|CHF|AUSF|SMF\"}[5m])))/(sum(irate(ocscp_metric_total_http_rx_req{ocscp_nf_type=~\"UDM|PCF|CHF|AUSF|SMF\"}[5m]))))*100"
    }
   ]
  },
  {
   "title": "Egress Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ocscp_metric_total_http_tx_req[2m]))",
     "legendFormat": "Egress Request Rate"
    },
    {
     "expr": "sum(irate(ocscp_metric_total_http_tx_req[2m])) by (ocscp_nf_type)",
     "legendFormat": "{{ocscp_nf_type}}"
    },
    {
     "expr": "sum(irate(ocscp_metric_total_http_tx_req{ocscp_nf_type=\"UDM\"}[2m])) by (ocscp_nf_end_point)"
    }
   ]
  },
  {
   "title": "Response Code Rate",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 7 },
   "targets": [
    {
     "expr": "sum(irate(ocscp_metric_total_http_rx_res_xx[2m])) by (ocscp_response_code_class)",
     "legendFormat": "Ingress {{ocscp_response_code_class}}xx"
    },
    {
     "expr": "sum(irate(ocscp_metric_total_http_tx_res_xx[2m])) by (ocscp_response_code_class)",
     "legendFormat": "Egress {{ocscp_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "Ingress Response Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ocscp_metric_total_http_rx_res_xx[5m])) ",
     "legendFormat": "Ingress Response Rate"
    },
    {
     "expr": "sum(irate(ocscp_metric_total_http_rx_res_xx[5m])) by (ocscp_nf_type)",
     "legendFormat": "{{ocscp_nf_type}}"
    },
    {
     "expr": "sum(irate(ocscp_metric_total_http_rx_res_xx[2m])) by (ocscp_response_code_class)",
     "legendFormat": "{{ocscp_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "Ingress/Downstream Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ocscp_http_0_0_0_80_downstream_cx_active)"
    }
   ]
  },
  {
   "title": "Egress Response Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ocscp_metric_total_http_tx_res_xx[2m]))",
     "legendFormat": "Egress Response Rate"
    },
    {
     "expr": "sum(irate(ocscp_metric_total_http_tx_res_xx[2m])) by (ocscp_nf_type)",
     "legendFormat": "{{ocscp_nf_type}}"
    },
    {
     "expr": "sum(irate(ocscp_metric_total_http_tx_res_xx[2m])) by (ocscp_response_code_class)",
     "legendFormat": "{{ocscp_response_code_class}}xx"
    },
    {
     "expr": "sum(irate(ocscp_metric_total_http_rx_req[5m])) by (ocscp_nf_type,ocscp_service_instance_id)",
     "legendFormat": "{{ocscp_nf_type}}"
    },
    {
     "expr": "sum(irate(ocscp_metric_total_http_tx_req{ocscp_nf_type=\"AUSF\"}[2m])) by (ocscp_nf_end_point)",
     "legendFormat": "{{ocscp_nf_type}}"
    }
   ]
  },
  {
   "title": "Egress/Upstream Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ocscp_cluster_defaultscp___3996e7d81a122f4fbef14b03f86c9da0_scp_upstream_cx_active{ocscp_cluster_name=\"outbound|31997||udm1-svc\"})"
    },
    {
     "expr": "sum(ocscp_cluster_defaultscp___afedc1545b09a3e4720f5f44c89039e3_scp_upstream_cx_active{ocscp_cluster_name=\"outbound|31835||udm2-svc\"})"
    },
    {
     "expr": "sum(ocscp_cluster_defaultscp___16c65bda685fd41891ce32693ce6c066_scp_upstream_cx_active{ocscp_cluster_name=\"outbound|32071||udm3-svc\"})"
    },
    {
     "expr": "sum(ocscp_cluster_defaultscp___2c66fb214700b4be5757aff9b09e35af_scp_upstream_cx_active{ocscp_cluster_name=\"outbound|30134||udm4-svc\"})"
    },
    {
     "expr": "sum(ocscp_cluster_defaultscp___311521c6012811869cdf84f135b3b6aa_scp_upstream_cx_active{ocscp_cluster_name=\"outbound|80||pcf5-svc\"})"
    },
    {
     "expr": "sum(ocscp_cluster_defaultscp___1b0c5f13b9c9885f7830ac3f2cb09e92_scp_upstream_cx_active{ocscp_cluster_name=\"outbound|80||pcf6-svc\"})"
    },
    {
     "expr": "sum(ocscp_cluster_defaultscp___5e14316e976f8e1cbfbe15bfb377c6ce_scp_upstream_cx_active{ocscp_cluster_name=\"outbound|80||pcf7-svc\"})"
    },
    {
     "expr": "sum(ocscp_cluster_defaultscp___5957ffbaa4da5b48e6ad517591ec1bbe_scp_upstream_cx_active{ocscp_cluster_name=\"outbound|80||pcf8-svc\"})"
    },
    {
     "expr": "sum(ocscp_cluster_defaultscp___6ec853bda331b46d0d9d5f1865c2e151_scp_upstream_cx_active{ocscp_cluster_name=\"outbound|80||chf9-svc\"})"
    },
    {
     "expr": "sum(ocscp_cluster_defaultscp___4bc8056a2d3ec34274e819e046690322_scp_upstream_cx_active{ocscp_cluster_name=\"outbound|80||chf10-svc\"})"
    },
    {
     "expr": "sum(ocscp_cluster_defaultscp___f2eacc891b01e6dbd798c89eb9862b07_scp_upstream_cx_active{ocscp_cluster_name=\"outbound|80||chf11-svc\"})"
    },
    {
     "expr": "sum(ocscp_cluster_defaultscp___6ea87eeecf3c8e28028f71e8f391d783_scp_upstream_cx_active{ocscp_cluster_name=\"outbound|80||chf12-svc\"})"
    },
    {
     "expr": "sum(ocscp_cluster_defaultscp___1d4a7e573f75e832686a7d63f055aca3_scp_upstream_cx_active{ocscp_cluster_name=\"outbound|80||ausf13-svc\"})"
    },
    {
     "expr": "sum(ocscp_cluster_defaultscp___f17fca31de2808fcfe2e69070e52d0b0_scp_upstream_cx_active{ocscp_cluster_name=\"outbound|80||ausf14-svc\"})"
    },
    {
     "expr": "sum(ocscp_cluster_defaultscp___1edc9117526b81ba86afce5a34535a22_scp_upstream_cx_active{ocscp_cluster_name=\"outbound|80||ausf15-svc\"})"
    },
    {
     "expr": "sum(ocscp_cluster_defaultscp___21bf435af14d695613497bdefc6f5fa6_scp_upstream_cx_active{ocscp_cluster_name=\"outbound|80||ausf16-svc\"})"
    },
    {
     "expr": "sum(ocscp_cluster_defaultscp___35a2129acc91d13110cc1006b48728f5_scp_upstream_cx_active{ocscp_cluster_name=\"outbound|80||smf17-svc\"})"
    },
    {
     "expr": "sum(ocscp_cluster_defaultscp___7cb8048f1172bfaaa67e27e5056bd15f_scp_upstream_cx_active{ocscp_cluster_name=\"outbound|80||smf18-svc\"})"
    },
    {
     "expr": "sum(ocscp_cluster_defaultscp___933dd3305382be1eed22f7bd4c927e6f_scp_upstream_cx_active{ocscp_cluster_name=\"outbound|80||smf19-svc\"})"
    },
    {
     "expr": "sum(ocscp_cluster_defaultscp___8a02ca63c051242a20316618193ed3ca_scp_upstream_cx_active{ocscp_cluster_name=\"outbound|80||smf20-svc\"})"
    }
   ]
  },
  {
   "title": "SCP CPU usage (sum-rate per service)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=\"front-envoy\"}[2m]))",
     "legendFormat": "scp-worker"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=\"discovery\"}[2m]))",
     "legendFormat": "scpc-pilot"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"scpc-ss.*\"}[2m]))",
     "legendFormat": "scpc-soothsayer"
    }
   ]
  },
  {
   "title": "SCP Total Replicas (sum per hpa)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_replicaset_status_ready_replicas{replicaset =~ 'scp-worker.*'}"
    }
   ]
  },
  {
   "title": "SCP Memory usage (sum-avg_over_time per service)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(container_memory_usage_bytes{pod_name=~\"scp-worker.*\"}[2m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "sum(avg_over_time(container_memory_usage_bytes{container_name=\"discovery\"}[2m]))",
     "legendFormat": "scpc-pilot"
    },
    {
     "expr": "sum(avg_over_time(container_memory_usage_bytes{pod_name=~\"scpc-soothsayer.*\"}[2m])) ",
     "legendFormat": "scpc-soothsayer"
    }
   ]
  },
  {
   "title": "CPU usage (sum-rate per Gen10 Worker Node)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"k8s-4.*\"}[2m])) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname }}"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"k8s-5.*\"}[2m])) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname }}"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"k8s-6.*\"}[2m])) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname }}"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"k8s-7.*\"}[2m])) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname }}"
    }
   ]
  },
  {
   "title": "Memory usage (sum per Gen10 Worker Node)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"k8s-4.*\"}) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname}}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"k8s-5.*\"}) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname}}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"k8s-6.*\"}) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname}}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"k8s-7.*\"}) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname}}"
    }
   ]
  },
  {
   "title": "CPU usage (sum-rate per Gen8 Worker Node)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"k8s-8.*\"}[2m])) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname }}"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"k8s-9.*\"}[2m])) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname }}"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"k8s-10.*\"}[2m])) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname }}"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"k8s-11.*\"}[2m])) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname }}"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"k8s-12.*\"}[2m])) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname }}"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"k8s-13.*\"}[2m])) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname }}"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"k8s-14.*\"}[2m])) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname }}"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"k8s-15.*\"}[2m])) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname }}"
    }
   ]
  },
  {
   "title": "Memory usage (sum per Gen8 Worker Node)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"k8s-8.*\"}) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname}}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"k8s-9.*\"}) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname}}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"k8s-10.*\"}) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname}}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"k8s-11.*\"}) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname}}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"k8s-12.*\"}) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname}}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"k8s-13.*\"}) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname}}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"k8s-14.*\"}) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname}}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"k8s-15.*\"}) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname}}"
    }
   ]
  },
  {
   "title": "CPU usage (sum-rate per ALL Master & Worker Node)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"k8s.*\"}[2m])) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname }}"
    }
   ]
  },
  {
   "title": "Memory usage (sum per ALL Master & Worker Node)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"k8s.*\"}) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname}}"
    }
   ]
  }
 ]
}